server:
  port: 8099

kafka:
  username: connect
  password: connect-secret
  host: 172.20.10.6:9092
  topic: kafka-topic-kmq
  group-id: kafka-group-id-gp
    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ola
    url: jdbc:postgresql://localhost:5432/salesDB
    
pagination-size:  5
pagination-in-pages: 0
